name: delayed_tween_animation_builder
description: Mimics the TweenAnimationBuilder but with an optional delay.
version: 0.5.1
repository: https://github.com/timcreatedit/delayed_tween_animation_builder

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: